os:
  - linux
  - osx
  - windows
language: node_js
node_js:
  - "8"
  - "9"
  - "10"
  - "11"
  - "12"
branches:
  only:
    - master
    - /^greenkeeper.*$/
before_script:
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then chmod +x ./cc-test-reporter; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then ./cc-test-reporter before-build; fi
script:
  - travis_wait 40 npm test
after_script:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; fi