os:
  - linux
  - osx
  - windows
addons:
  homebrew:
    packages:
    - bash
language: node_js
node_js:
  - "8"
  - "9"
  - "10"
  - "11"
branches:
  only:
    - master
    - /^greenkeeper.*$/
script:
  - travis_wait 40 npm test