os:
  - linux
  - osx
  - windows
language: node_js
node_js:
  - "8"
  - "9"
  - "10"
  - "11"
branches:
  only:
    - master
    - /^greenkeeper.*$/
    - "/^v[0-9]+\\.[0-9]+\\.[0-9]+-(alpha|beta|rc)\\.[0-9]+$/"
    - "/^v[0-9]+\\.[0-9]+\\.[0-9]+$/"

before_deploy:
  - npm run gh:release

deploy:
  provider: releases
  api_key: "$CONVENTIONAL_GITHUB_RELEASER_TOKEN"
  on:
    tags: true
