os:
  - linux
  - osx
  - windows
language: node_js
node_js:
  - "8"
  - "9"
  - "10"
  - "11"
branches:
  only:
    - master
    - /^greenkeeper.*$/
# See https://stackoverflow.com/questions/1570262/get-exit-code-of-a-background-process?answertab=votes#tab-top
# See https://github.com/travis-ci/travis-ci/issues/7323#issuecomment-411563149
script:
  - npm test &
  - TEST_PID=$!
  - while [ -e /proc/$TEST_PID ]; do echo -n "."  && sleep 60; done
  - TEST_CODE="$(wait $TEST_PID)"
  - exit $TEST_CODE 